FROM nimlang/nim

WORKDIR /usr/local/app

RUN mkdir out
COPY src src

COPY packages.json packages.json
# RUN echo y | nimble install nim-amqp

CMD ["nim", "c", "-o:out/main", "-r", "src/main.nim"]
EXPOSE 3000/tcp