FROM alpine:latest

RUN apk add curl
RUN apk add mongo-c-driver
RUN curl -sO https://ziglang.org/download/0.15.2/zig-aarch64-linux-0.15.2.tar.xz
RUN tar -xf zig-aarch64-linux-0.15.2.tar.xz -C /usr/local/bin

WORKDIR /usr/local/app

COPY mongo_libs mongo_libs
COPY src src
COPY build.zig .
COPY build.zig.zon .

CMD ["/usr/local/bin/zig-aarch64-linux-0.15.2/zig", "build", "run", "-Doptimize=ReleaseSafe"]
EXPOSE 21991
